<%
Dim Action_Plugin_FileManage_Initialize()
ReDim Action_Plugin_FileManage_Initialize(0)
Dim bAction_Plugin_FileManage_Initialize
Dim sAction_Plugin_FileManage_Initialize


Dim Action_Plugin_FileManage_Terminate()
ReDim Action_Plugin_FileManage_Terminate(0)
Dim bAction_Plugin_FileManage_Terminate
Dim sAction_Plugin_FileManage_Terminate

Dim Action_Plugin_FileManage_ExportSiteFileList_Begin()
ReDim Action_Plugin_FileManage_ExportSiteFileList_Begin(0)
Dim bAction_Plugin_FileManage_ExportSiteFileList_Begin
Dim sAction_Plugin_FileManage_ExportSiteFileList_Begin

Dim Action_Plugin_FileManage_ExportSiteFileList_End()
ReDim Action_Plugin_FileManage_ExportSiteFileList_End(0)
Dim bAction_Plugin_FileManage_ExportSiteFileList_End
Dim sAction_Plugin_FileManage_ExportSiteFileList_End

Dim Action_Plugin_FileManage_GetTypeIco_Begin()
ReDim Action_Plugin_FileManage_GetTypeIco_Begin(0)
Dim bAction_Plugin_FileManage_GetTypeIco_Begin
Dim sAction_Plugin_FileManage_GetTypeIco_Begin

Dim Action_Plugin_FileManage_GetTypeIco_End()
ReDim Action_Plugin_FileManage_GetTypeIco_End(0)
Dim bAction_Plugin_FileManage_GetTypeIco_End
Dim sAction_Plugin_FileManage_GetTypeIco_End

Dim Action_Plugin_FileManage_ExportSiteFileEdit_Begin()
ReDim Action_Plugin_FileManage_ExportSiteFileEdit_Begin(0)
Dim bAction_Plugin_FileManage_ExportSiteFileEdit_Begin
Dim sAction_Plugin_FileManage_ExportSiteFileEdit_Begin

Dim Action_Plugin_FileManage_ExportSiteFileEdit_End()
ReDim Action_Plugin_FileManage_ExportSiteFileEdit_End(0)
Dim bAction_Plugin_FileManage_ExportSiteFileEdit_End
Dim sAction_Plugin_FileManage_ExportSiteFileEdit_End

Dim Action_Plugin_FileManage_DeleteSiteFile_Begin()
ReDim Action_Plugin_FileManage_DeleteSiteFile_Begin(0)
Dim bAction_Plugin_FileManage_DeleteSiteFile_Begin
Dim sAction_Plugin_FileManage_DeleteSiteFile_Begin

Dim Action_Plugin_FileManage_DeleteSiteFile_End()
ReDim Action_Plugin_FileManage_DeleteSiteFile_End(0)
Dim bAction_Plugin_FileManage_DeleteSiteFile_End
Dim sAction_Plugin_FileManage_DeleteSiteFile_End

Dim Action_Plugin_FileManage_DownloadFile_Begin()
ReDim Action_Plugin_FileManage_DownloadFile_Begin(0)
Dim bAction_Plugin_FileManage_DownloadFile_Begin
Dim sAction_Plugin_FileManage_DownloadFile_Begin

Dim Action_Plugin_FileManage_DownloadFile_End()
ReDim Action_Plugin_FileManage_DownloadFile_End(0)
Dim bAction_Plugin_FileManage_DownloadFile_End
Dim sAction_Plugin_FileManage_DownloadFile_End


Dim Action_Plugin_FileManage_RenameFile_Begin()
ReDim Action_Plugin_FileManage_RenameFile_Begin(0)
Dim bAction_Plugin_FileManage_RenameFile_Begin
Dim sAction_Plugin_FileManage_RenameFile_Begin

Dim Action_Plugin_FileManage_RenameFile_End()
ReDim Action_Plugin_FileManage_RenameFile_End(0)
Dim bAction_Plugin_FileManage_RenameFile_End
Dim sAction_Plugin_FileManage_RenameFile_End

Dim Action_Plugin_FileManage_CheckFolder_Begin()
ReDim Action_Plugin_FileManage_CheckFolder_Begin(0)
Dim bAction_Plugin_FileManage_CheckFolder_Begin
Dim sAction_Plugin_FileManage_CheckFolder_Begin

Dim Action_Plugin_FileManage_CheckFolder_End()
ReDim Action_Plugin_FileManage_CheckFolder_End(0)
Dim bAction_Plugin_FileManage_CheckFolder_End
Dim sAction_Plugin_FileManage_CheckFolder_End

Dim Action_Plugin_FileManage_ExportSiteUpload_Begin()
ReDim Action_Plugin_FileManage_ExportSiteUpload_Begin(0)
Dim bAction_Plugin_FileManage_ExportSiteUpload_Begin
Dim sAction_Plugin_FileManage_ExportSiteUpload_Begin

Dim Action_Plugin_FileManage_ExportSiteUpload_End()
ReDim Action_Plugin_FileManage_ExportSiteUpload_End(0)
Dim bAction_Plugin_FileManage_ExportSiteUpload_End
Dim sAction_Plugin_FileManage_ExportSiteUpload_End

Dim Action_Plugin_FileManage_Upload_Begin()
ReDim Action_Plugin_FileManage_Upload_Begin(0)
Dim bAction_Plugin_FileManage_Upload_Begin
Dim sAction_Plugin_FileManage_Upload_Begin

Dim Action_Plugin_FileManage_Upload_End()
ReDim Action_Plugin_FileManage_Upload_End(0)
Dim bAction_Plugin_FileManage_Upload_End
Dim sAction_Plugin_FileManage_Upload_End

Dim Action_Plugin_FileManage_PostSiteFile_Begin()
ReDim Action_Plugin_FileManage_PostSiteFile_Begin(0)
Dim bAction_Plugin_FileManage_PostSiteFile_Begin
Dim sAction_Plugin_FileManage_PostSiteFile_Begin

Dim Action_Plugin_FileManage_PostSiteFile_End()
ReDim Action_Plugin_FileManage_PostSiteFile_End(0)
Dim bAction_Plugin_FileManage_PostSiteFile_End
Dim sAction_Plugin_FileManage_PostSiteFile_End

Dim Action_Plugin_FileManage_CreateFolder_Begin()
ReDim Action_Plugin_FileManage_CreateFolder_Begin(0)
Dim bAction_Plugin_FileManage_CreateFolder_Begin
Dim sAction_Plugin_FileManage_CreateFolder_Begin

Dim Action_Plugin_FileManage_CreateFolder_End()
ReDim Action_Plugin_FileManage_CreateFolder_End(0)
Dim bAction_Plugin_FileManage_CreateFolder_End
Dim sAction_Plugin_FileManage_CreateFolder_End

Dim Action_Plugin_FileManage_GetSize_Begin()
ReDim Action_Plugin_FileManage_GetSize_Begin(0)
Dim bAction_Plugin_FileManage_GetSize_Begin
Dim sAction_Plugin_FileManage_GetSize_Begin

Dim Action_Plugin_FileManage_GetSize_End()
ReDim Action_Plugin_FileManage_GetSize_End(0)
Dim bAction_Plugin_FileManage_GetSize_End
Dim sAction_Plugin_FileManage_GetSize_End

Dim Action_Plugin_FileManage_ExportInformation_Begin()
ReDim Action_Plugin_FileManage_ExportInformation_Begin(0)
Dim bAction_Plugin_FileManage_ExportInformation_Begin
Dim sAction_Plugin_FileManage_ExportInformation_Begin

Dim Action_Plugin_FileManage_ExportInformation_End()
ReDim Action_Plugin_FileManage_ExportInformation_End(0)
Dim bAction_Plugin_FileManage_ExportInformation_End
Dim sAction_Plugin_FileManage_ExportInformation_End

Dim Action_Plugin_FileManage_ExportInformation_NotFound()
ReDim Action_Plugin_FileManage_ExportInformation_NotFound(0)
Dim bAction_Plugin_FileManage_ExportInformation_NotFound
Dim sAction_Plugin_FileManage_ExportInformation_NotFound

Dim Action_Plugin_FileManage_GetTypeIco_NotFound()
Redim Action_Plugin_FileManage_GetTypeIco_NotFound(0)
Dim bAction_Plugin_FileManage_GetTypeIco_NotFound
Dim sAction_Plugin_FileManage_GetTypeIco_NotFound

Dim Action_Plugin_FileManage_AddControlBar
Redim Action_Plugin_FileManage_AddControlBar(0)
Dim sAction_Plugin_FileManage_AddControlBar
Dim bAction_Plugin_FileManage_AddControlBar

Dim Action_Plugin_FileManage_AddControlList
Redim Action_Plugin_FileManage_AddControlList(0)
Dim sAction_Plugin_FileManage_AddControlList
Dim bAction_Plugin_FileManage_AddControlList

Dim Action_Plugin_FileManage_FileOpenType
Redim Action_Plugin_FileManage_FileOpenType(0)
Dim sAction_Plugin_FileManage_FileOpenType
Dim bAction_Plugin_FileManage_FileOpenType
%>